### ISSUE TITLE
Ensure a clean ReaderGroup before starting a benchmark

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega-benchmark#37]
**Problem description**
If the benchmark process is abruptly restarted, it may not be able to close the working `Reader`s and clean up the `ReaderGroup` (e.g., a benchmark runs in a k8 pod and it gets restarted). With the current logic, the benchmark will not be able of restarting the readers as the previous execution did not took care of closing the opened resources (see https://github.com/pravega/pravega-operator/issues/139). 

**Problem location**
`PravegaPerfTest`

**Suggestions for an improvement**
Make sure in `PravegaPerfTest` of checking if there are open `Reader`s left from a previous execution, and close them before creating the readers for the next execution.

**Comment by fpj** [comment]
As I think about this tool, we should not really be restarting it. A performance tool should run through completion and produce some output numbers. Restarts are expected with real applications. Consequently, I'd like to understand why we are talking about restarts here.

Also, we are closing the reader:

https://github.com/pravega/pravega-benchmark/blob/1d90a1ffbcd85370d6aa280fa7fb69c06218a1e3/src/main/java/io/pravega/perf/PravegaReaderWorker.java#L51

but we are not invoking `readerOffline` which is needed to declare the reader out of the group. I want to clarify because I'm not seeing it mentioned in the description.

**Comment by RaulGracia** [comment]
Thanks @fpj, I have two comments here:
1) While this needs to be confirmed by the QA team, the most likely cause for the abrupt re-execution of the benchmark we are seeing is that the pod executing the benchmark is restarted. Otherwise, we need more details on how this test is being executed.
2) I think that `reader.close()` in `EventStreamReaderImpl` internally calls `groupState.readerShutdown(getPosition());`, which transaltes into `ReaderGroupStateManager.readerShutdown()`. The call to `readerOffline()` is analogous to `ReaderGroupStateManager.readerShutdown()`. So, I think that calling `reader.close()` may be enough for removing the reader from the `ReaderGroup`.
